name: Deploy react app

on:
  push:
    Branches:
      - main

on:
  pull_request:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build dist
        run: npm run build

      - name: ESLint
        run: npx run lint

      - name: Setup pages
        uses: actions/configure-pages@v4
      - name: upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"

      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1

      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge to main from dev."
          exit 1
